### ISSUE TITLE
Style CSS on React

### ISSUE THREAD

**Issue by olavkwan** [ahmadfaqih796/React-Fundamentals#1]
Bagaimana cara mengimplementasikan css di react?? Thx

Warm Regards

Olavkwan

**Comment by ahmadfaqih796** [comment]
> Bagaimana cara mengimplementasikan css di react?? Thx
> 
> Warm Regards
> 
> Olavkwan

Cara cukup mudah mas, tinggal panggil importnya dengan ketik `import "<tempat cssnya yang disimpan>"`

**Comment by olavkwan** [comment]
> > Bagaimana cara mengimplementasikan css di react?? Thx
> > Warm Regards
> > Olavkwan
> 
> Cara cukup mudah mas, tinggal panggil importnya dengan ketik `import "<tempat cssnya yang disimpan>"`

Baiik mas Faqih infonya.. trims
